---
name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  actions: read
  checks: write
  contents: read
  issues: read
  packages: read
  pull-requests: write
  statuses: read
  security-events: write

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: 'temurin'

      - name: Cache Gradle Resources
        uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build (Linux/macOS)
        if: runner.os != 'Windows'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew -Dtestfx.headless=true versions check

      - name: Build (Windows)
        if: runner.os == 'Windows'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          .\gradlew -Dtestfx.headless=true versions check
        shell: cmd

      - name: Publish Test Results (Linux)
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: runner.os == 'Linux'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results (${{ runner.os }})
          report_individual_runs: true
          check_run_annotations_branch: master
          check_run_annotations: all tests, skipped tests
          files: subprojects/**/build/test-results/**/*.xml

      - name: Publish Test Results (macOS)
        uses: EnricoMi/publish-unit-test-result-action/macos@v2
        if: runner.os == 'macOS'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results (${{ runner.os }})
          report_individual_runs: true
          check_run_annotations_branch: master
          check_run_annotations: all tests, skipped tests
          files: subprojects/**/build/test-results/**/*.xml

      - name: Publish Test Results (Windows)
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: runner.os == 'Windows'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Unit Test Results (${{ runner.os }})
          report_individual_runs: true
          check_run_annotations_branch: master
          check_run_annotations: all tests, skipped tests
          files: subprojects/**/build/test-results/**/*.xml

      - name: Publish Snapshots
        if: github.ref == 'refs/heads/master' && runner.os == 'Linux'
        run: |
          ver=$(./gradlew properties -q | grep "version:" | awk '{print $2}')
          if [[ $ver == *"SNAPSHOT"* ]] 
          then
              ./gradlew publish -PgluonNexusDeployUsername=$NEXUS_USERNAME -PgluonNexusDeployPassword=$NEXUS_PASSWORD
          fi
        shell: bash
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
